import { useState, useRef, useEffect } from 'react';
import axios from 'axios';
import { INITIAL_BOT_MESSAGE } from '../../constants/chatConstants';

const API_BASE = process.env.REACT_APP_API_URL;

export default function useChat() {
  //Declare state variables for messages, input, and loading status11
  const [messages, setMessages] = useState([INITIAL_BOT_MESSAGE]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  //2ND PARMATER TELLS WHENEVER MESSAGES CHANGE, RUN THIS FUNCTION (SCROLL TO BOTTOM) — ensures that the chat view automatically scrolls to the latest message whenever a new message is added to the chat. This is important for maintaining a good user experience, especially in a chat interface where new messages can come in frequently.
  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const sendMessage = async (e) => {
    if (e?.preventDefault) e.preventDefault();
    if (!input.trim()) return;

    const userMessage = input;
    //Add new user message to the messages state — this updates the chat interface immediately with the user's message before waiting for the AI response. This is done by creating a new array that includes all previous messages (using the spread operator ...prev) and appending a new message object with type 'user' and the text of the user's message.
    setMessages((prev) => [...prev, { type: 'user', text: userMessage }]);
    setInput('');
    setLoading(true);

    try {
      if (!API_BASE) {
        throw new Error('REACT_APP_API_URL is undefined. Check your .env file and restart the dev server.');
      }

      //Sending NON Async Request to Backend API: This line sends a POST request to the backend API with the user's message. The API is expected to process the message and return a response from the AI model, along with any relevant SQL query and results if applicable.
      const response = await axios.post(API_BASE, { message: userMessage });
    //Will wait for above line execution
    /*
      This is an object destructuring assignment that reads properties off response.data. It takes the response property and stores it in a new local variable named aiResponse (response: aiResponse), and also extracts sqlQuery and results into same-named local variables.
      The expected structure of response.data is:
      {
        response: "The AI's response text",
        sqlQuery: "The SQL query generated by the AI",
        results: "The results of the SQL query"
      }
      */
      const { response: aiResponse, sqlQuery, results } = response.data;
      //Update messages state with the AI's response, including the SQL query and results if available. This adds a new message object to the messages array with type 'bot', the text of the AI's response, and optionally the SQL query and results.
      
      setMessages((prev) => [...prev, { type: 'bot', text: aiResponse, sql: sqlQuery, data: results }]);
    } catch (error) {
      console.error('Chat error:', error);
      setMessages((prev) => [
        ...prev,
        {
          type: 'bot',
          text: 'Error: ' + (error.response?.data?.error || 'I am unable to get the response. You can try again!'),
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  return {
    messages,
    input,
    setInput,
    loading,
    sendMessage,
    messagesEndRef,
  };
}
